package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'DockerTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("DockerTest")) {
    expectSteps {
        script {
            name = "one"
            scriptContent = "npm -v"
            dockerImage = "nodejs"
            dockerPull = true
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            dockerImage = ""
        }
    }
}
